import React, { useState } from 'react';
import { Play, ArrowRight, Music, Users, Menu, X } from 'lucide-react';
import { assets } from '../assets/assets';
import { Link } from 'react-router-dom';

const MuseLandingPage = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const navItems = ['GENERATE MUSIC', 'AI TOOLS', 'LICENSE', 'API', 'BUSINESS'];

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white font-sans selection:bg-[#a3ff12] selection:text-black overflow-x-hidden">
      {/* Navbar */}
      <nav className="flex justify-between items-center px-6 md:px-12 py-6 relative z-50">
        <div className="h-12 w-12 md:h-16 md:w-16">
          <img className='h-full w-full object-contain' src={assets.logo2} alt="Logo" />
        </div>

        {/* Desktop Nav */}
        <div className="hidden lg:flex gap-8 text-sm font-semibold opacity-70">
          {navItems.map((item) => (
            <a href="#" key={item} className="hover:text-[#a3ff12] transition-colors">{item}</a>
          ))}
        </div>

        <div className="flex items-center gap-3 md:gap-6">
          <div className="hidden sm:flex gap-4">
            <Link to="/login" className="bg-green-200 text-black px-4 md:px-6 py-2 rounded-full text-[10px] md:text-xs font-bold tracking-widest hover:scale-105 transition-transform">
              SIGN IN
            </Link>
            <Link to="/register" className="bg-green-500 text-black px-4 md:px-6 py-2 rounded-full text-[10px] md:text-xs font-bold tracking-widest hover:scale-105 transition-transform">
              SIGN UP
            </Link>
          </div>
          
          {/* Mobile Menu Toggle */}
          <button className="lg:hidden p-2" onClick={() => setIsMenuOpen(!isMenuOpen)}>
            {isMenuOpen ? <X size={28} /> : <Menu size={28} />}
          </button>
        </div>

        {/* Mobile Slide-out Menu */}
        {isMenuOpen && (
          <div className="absolute top-full left-0 w-full bg-[#111] border-b border-white/10 p-8 flex flex-col gap-6 lg:hidden animate-in slide-in-from-top duration-300">
            {navItems.map((item) => (
              <a href="#" key={item} className="text-xl font-bold hover:text-[#a3ff12]">{item}</a>
            ))}
            <div className="flex flex-col gap-4 pt-4 border-t border-white/10">
                <Link to="/login" className="text-center bg-green-200 text-black py-3 rounded-full font-bold">SIGN IN</Link>
                <Link to="/register" className="text-center bg-green-500 text-black py-3 rounded-full font-bold">SIGN UP</Link>
            </div>
          </div>
        )}
      </nav>

      {/* Hero Section */}
      <main className="px-6 md:px-12 lg:px-24 py-10 lg:py-20 flex flex-col lg:flex-row items-center justify-between gap-12">

        {/* Left Side: Copy */}
        <div className="max-w-2xl z-20 text-center lg:text-left">
          <p className="text-[10px] md:text-sm tracking-[0.2em] mb-4 opacity-60 uppercase">Listen to unique, royalty-free music in seconds</p>
          <h1 className="text-6xl md:text-8xl lg:text-9xl font-black leading-[0.85] tracking-tighter mb-8">
            MUSE<br /><span className="text-gray-500">...</span>
          </h1>
          <p className="text-lg md:text-xl text-gray-400 mb-10 max-w-md mx-auto lg:mx-0">Limitless soundscapes generated by cutting-edge intelligence.</p>

          <div className="bg-[#1a1a1a] p-5 md:p-8 rounded-3xl border border-[#333] inline-block shadow-2xl animate-bounce-subtle">
            <div className="flex items-center justify-center lg:justify-start gap-4 mb-6">
              <div className="p-2 md:p-3 bg-gray-700 rounded-full border border-gray-600">
                <Play size={24} className="text-green-500 fill-green-500" />
              </div>
              <span className="font-mono text-[10px] md:text-xs tracking-widest opacity-80">START LISTENING NOW</span>
            </div>
            <div className="flex flex-col sm:flex-row gap-3">
              <button className="bg-white text-black px-8 py-4 rounded-full flex items-center justify-center gap-2 font-bold hover:bg-green-500 transition-colors">
               <Link to = "/home">
               Discover
               </Link>
                
                 <ArrowRight size={18} />
              </button>
              <button className="bg-[#2a2a2a] text-white px-8 py-4 rounded-full font-bold border border-gray-600 hover:border-green-500 transition-all">
                Connect
              </button>
            </div>
          </div>
        </div>

        {/* Right Side: Visual Element */}
        <div className="relative flex justify-center items-center w-full lg:w-1/2">
          {/* Neon Glow */}
          <div className="absolute w-[80%] aspect-square bg-green-500 opacity-10 blur-[100px] md:blur-[200px] rounded-full animate-pulse" />

          {/* Hero Circle - Responsive sizing using aspect-ratio */}
          <div className="relative z-10 w-full max-w-[350px] md:max-w-[500px] lg:max-w-[600px] aspect-square rounded-full border border-white/10 overflow-hidden shadow-2xl bg-black">
            <div
              className="w-full h-full bg-cover bg-center transition-transform duration-700 hover:scale-110"
              style={{ backgroundImage: "url('/logo1.png')" }}
            />
          </div>
        </div>
      </main>

      {/* Footer / Stats Bar */}
      <footer className="px-6 md:px-12 py-10 flex flex-wrap justify-center lg:justify-start gap-8 md:gap-12 opacity-50 text-[10px] md:text-sm font-mono">
        <div className="flex items-center gap-2"><Users size={16} /> 200,000+ USERS</div>
        <div className="flex items-center gap-2"><Music size={16} /> 500,000+ CREATORS</div>
      </footer>

      {/* Custom Styles for Animation */}
      <style dangerouslySetInnerHTML={{ __html: `
        @keyframes bounce-subtle {
          0%, 100% { transform: translateY(-5%); }
          50% { transform: translateY(0); }
        }
        .animate-bounce-subtle {
          animation: bounce-subtle 3s infinite ease-in-out;
        }
      `}} />
    </div>
  );
};

export default MuseLandingPage;